name: Build for Raspberry Pi (Docker)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            --platform linux/arm/v7 \
            rust:latest bash -c "
              # Install system dependencies
              apt-get update && apt-get install -y \
                pkg-config \
                libglib2.0-dev \
                libgstreamer1.0-dev \
                libgstreamer-plugins-base1.0-dev \
                libgstreamer-plugins-good1.0-dev \
                libgstreamer-plugins-bad1.0-dev && \
              
              # Build the project
              cargo build --release
            "

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-binary-docker
          path: target/release/*
          retention-days: 5
