name: Build Pi Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          docker build -t rusty-cam-builder .
          docker run --rm -v $(pwd)/target:/app/target rusty-cam-builder

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: rusty-cam-binary
          path: target/aarch64-unknown-linux-gnu/release/rusty-cam
