name: Build for Raspberry Pi

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install cross
        run: cargo install cross

      - name: Build for armv7
        run: cross build --target armv7-unknown-linux-gnueabihf --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-binary
          path: target/armv7-unknown-linux-gnueabihf/release/rust-cam
